kind: pipeline
type: kubernetes
name: default

metadata:
  namespace: drone

workspace:
  base: /drone/src
  path: /drone/src/drone-ci-conde

steps:

- name: ping
  image: redis
  commands:
  - redis-cli -h 127.0.0.1 ping

services:
- name: cache
  image: redis


- name: backend
  image: golang
  resources:
    requests:
      cpu: 250
      memory: 250MiB
    limits:
      cpu: 500
      memory: 500MiB
  commands:
  - go build
  - go test

- name: Creating an Image
  image: plugins/ecr
  environment:
   PLUGIN_STORAGE_DRIVER: overlay2
  settings:
   repo: 044418114861.dkr.ecr.eu-central-1.amazonaws.com/gql-testrepo
   access_key:
    from_secret: aws_access_key_id
   secret_key:
    from_secret: aws_secret_access_key
   registry: 044418114861.dkr.ecr.eu-central-1.amazonaws.com
   auth:
    from_secret: auth_token
   dockerfile: /drone/src/drone-ci-conde/docker-projects/Dockerfile
   context: /drone/src/drone-ci-conde/docker-projects/
   region: eu-central-1
   tags:
    - 2.0



- name: deliver
  image: sinlead/drone-kubectl
  settings:
   kubernetes_server:
     from_secret: k8s_server
   kubernetes_cert:
     from_secret: k8s_cert
   kubernetes_token:
     from_secret: k8s_token
  commands:
   - kubectl apply -f deployment.yml 
