kind: pipeline
type: kubernetes
name: default

metadata:
  namespace: drone

steps:
- name: backend
  image: golang
  resources:
    requests:
      cpu: 250
      memory: 250MiB
    limits:
      cpu: 500
      memory: 500MiB
  commands:
  - go build
  - go test
  - go run main.go -http=:3000
