kind: pipeline
type: kubernetes
name: default

metadata:
  namespace: drone

workspace:
  base: /drone/src
  path: /drone/src/drone-ci-conde

steps:

- name: Creating an Image
  image: plugins/ecr
  settings:
   repo: 044418114861.dkr.ecr.eu-central-1.amazonaws.com/gql-testrepo
   access_key:
    from_secret: aws_access_key_id
   secret_key:
    from_secret: aws_secret_access_key
   registry: 044418114861.dkr.ecr.eu-central-1.amazonaws.com
   volumes:
   - name: cache
     path: /drone/src/drone-ci-conde/docker-projects/
   auth:
    from_secret: auth_token
   dockerfile: /drone/src/drone-ci-conde/docker-projects/Dockerfile
   context: /drone/src/drone-ci-conde/docker-projects/
   storage_driver: overlay
   region: eu-central-1
   tags:
    - 2.0
    - latest



- name: deploy
  image: sinlead/drone-kubectl
  settings:
   kubernetes_server:
    from_secret: k8s_secret
   kubernetes_cert:
    from_secret: k8s_cert
   kubernetes_token:
    from_token: k8s_token
  commands:
   - kubectl create -f deployment.yml 
  environment:
   DRONE_SERVICE_ACCLOUNT_DEFAULT: drone-deploy

volumes:
- name: cache
  temp: {}
