kind: pipeline
type: kubernetes
name: default

metadata:
  namespace: drone

steps:
- name: backend
  image: golang
  commands:
  - go build
  - go test

- name: frontend
  image: node
  commands:
  - npm install
  - npm test
